### PR TITLE
BCMOHAD-25319-Permission Set

### PR DESCRIPTION
**Pull request by mhussaincgi**

### CODE REVIEW

**Review by RanadheerRG — APPROVED** [review]
@mhussaincgi  Approved

**Review by cgijeffolsen — APPROVED** [review]
approved for BAR admin @mhussaincgi 
@RanadheerRG @NataliaNikishina

**Review by NataliaNikishina — CHANGES_REQUESTED** [review]
@mhussaincgi  The PS needs to be committed under src-access-mgmt/main/default folder to ensure the successful deployment. Please move the metadata to the correct folder. Thanks!

**Comment by mhussaincgi** [comment]
> @mhussaincgi The PS needs to be committed under src-access-mgmt/main/default folder to ensure the successful deployment. Please move the metadata to the correct folder. Thanks!

@NataliaNikishina  Please review. I have update the location accordingly.

**Review by NataliaNikishina — APPROVED** [review]
@mhussaincgi approved

**Pull request merged**
